application: iosysceod
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /turn.*
  script: turn.app
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: "1.2"
